### ISSUE TITLE
Imposible to match strings ? 

### ISSUE THREAD

**Issue by justnorris** [fshost/node-dir#10]
~~~
/node_modules/node-dir/lib/readfiles.js:82
                    if (options.exclude && options.exclude.test(filename)) ret
                                                           ^
TypeError: Object node_modules,test has no method 'test'
~~~

My config was:
~~~
{ exclude: ['node_modules', 'test'] }
~~~

Doesn't seem to work with arrays at all, only regex is accepted ? In that case the docs need updating...

**Comment by fshost** [comment]
The error you have indicated appears to be from an early version.  Make sure you are using the latest version when installing from NPM. If your using this as a dependency in your package make sure you are using 0.1.8 or higher. There are tests now for both regexes and arrays of string and both work.
