### ISSUE TITLE
Permission errors occur if OSX .Trashes directory exists

### ISSUE THREAD

**Issue by tkdan235** [fshost/node-dir#11]
When using dir.files to get an array of file in a dir, and in that dir a `.Trashes` dir exists, I get the following:

```
/Users/Sam/Projects/bin/slurp.js:59
                if (err) throw err;
                               ^
Error: EACCES, readdir '/Volumes/Media/.Trashes'
```

**Comment by fshost** [comment]
Thanks for the PR.  Looking at #13 it appears that commit 204793b should have fixed this issue.  If this is still an issue for some reason I'll reopen it but I believe we can close this issue now.

**Comment by fshost** [comment]
Actually I'll need to bump the NPM version number so I'm reopening until that has been published.
