### ISSUE TITLE
Options for all methods

### ISSUE THREAD

**Issue by louisameline** [fshost/node-dir#12]
Hello and thank you for your work.

A suggestion : it would be nice to have an `options` second parameter for all methods.
The first option that comes to mind for all methods would be the possibility to prevent recursion or set a max number of recursions.
Thank you.

**Comment by fshost** [comment]
I've considered this, but realized that avoiding recursion can be done by simply using node's built-in methods with a single callback.  This library was not meant to be a replacement for node's already robust file system methods, but to reduce the complexity of recursing through multiple levels of subdirs.  That being said, I suppose if there was enough requests for this and/or some contribution to add it in a pull request (with tests) I might revisit this.  Thanks for your input though. :)
