### ISSUE TITLE
Implement...

### ISSUE THREAD

**Issue by jaider2523** [fshost/node-dir#21]
How to use the options.....for  example: shortName:

dir.subdirs(path, { shortName: true},  function(err, subdirs) {
    if (err) throw err;
    console.log(subdirs);
}); 

Don't work......matchDir: 'name' ....Don't work

**Comment by fshost** [comment]
The subdirs method does not have an options parameter as you can easily sort and/or filter the array of subdirs returned using native Array methods.  There are examples of this for the files method in the readme but they would also apply to subdirs, e.g. subdirs.sort(), subdirs.filter(yourFunction), etc.
