### ISSUE TITLE
EPERM error 

### ISSUE THREAD

**Issue by Coretool** [fshost/node-dir#23]
When I try to use dir.paths on "F:\" I get the following error! How can I fix it ? 

`Error: EPERM: operation not permitted, stat 'F:\found.000'
    at Error (native)`

**Comment by fshost** [comment]
is F:\found.000 a file, and if so, does your node app have read permissions for it?

**Comment by Coretool** [comment]
I executed it with root permission (on windows admin), isn't that enough ?

**Comment by fshost** [comment]
Its possible that admin might not have read access to a file in Windows and the error sounds like a read permission issue. Can you check the file permissions for it, and if possible, set the read permission for the user or group (presumably Administrators) running the node process? Alternatively, you could try adding an exclude option for that file.
