### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by Krisa** [fshost/node-dir#25]
About readFiles. The module is very flexible and works well, but it suffers at the same time of some performance issue. The directories are read sequentially, in one order or the other, which is sometimes wished for some cases, but for others, especially when it comes to performance, it may not matter that the files are read in a special order. Also, the use of "stats" could be tweaked relatively easily.

So first, to test the performance, I have created a small test with one directory and lots of subdirectories, and in each directory, there is a simple file - (many bad practices to create this test, but this doesn't need to be fast here :) ):
```javascript
var Promise = require('bluebird');
var fs = Promise.promisifyAll( require('fs') );
var dir = require('node-dir');

fs.mkdirSync("tmp");
for (var i = 10000; i--; ) {
  fs.mkdirSync("tmp/" + i);
}
console.log("dir created");
for (var i = 10000; i--; ) {
  fs.writeFileSync("tmp/" + i + "/file.txt", "hello", "utf8");
}
console.log("files created");
```

I have first tried with promise:
```javascript
console.time('diff time');
fs.readdirAsync("tmp").map(function(dir) {
  return fs.readdirAsync("tmp/" + dir).map(function(file) {
      return fs.readFileAsync("tmp/" + dir + "/" + file, "utf8");
    });
}).then(function(fileContent) {
  console.timeEnd('diff time');
});
```
And the execution time on my machine is always between 900ms and 1100ms.

To compare, I have created following code:
```javascript
dir.readFiles("tmp",
    function(err, content, filename, next) {
        if (err) throw err;
        next();
    },
    function(err, files){
        if (err) throw err;
        console.timeEnd('diff time2');
    });
```
The execution time is always between 2800ms and 3300ms. Roughly 3 times slower.

One of the reason is for sure, that I'm not using stat() to test, whether there is a directory or not. Maybe one of the easy tweak to boost the performance would be an option to consider that a file without extension (no "." in the name) is a directory. Of course this should be an option, it's not always possible to predict what is expected, and a file without extension might exist. So, for the sake of consistency, I have tried to make (a useless) stat() call in my promise code:
```javascript
console.time('diff time');
fs.readdirAsync("tmp").map(function(dir) {
  return fs.readdirAsync("tmp/" + dir).map(function(file) {
      return fs.statAsync("tmp/" + dir + "/" + file).then(function(stat) {
        if(stat.isFile())
          return fs.readFileAsync("tmp/" + dir + "/" + file, "utf8");
      });
      
    });
}).then(function(fileContent) {
  console.timeEnd('diff time');
});
```
And, well, this is slower, as expected, and it takes now 1300 to 1500ms, so roughly 40% slower, which is still (more than) double faster than reading the directory with `node-dir`.

So now I guess the difference between 1300/1500ms and 2800/3300ms is caused by the sequential read of the directory. I'm aware that, unlike for fs.stat(), this change is quite massive but ... it would be really great :)

**Comment by fshost** [comment]
You make some good points.  I originally wrote this module primarily to deal with sequential processing of files that could involve sorting and the like but it might make sense to at least add an option to process them in a non-sequential manner for those who don't need that and want better performance.  I'm not sure about the idea for identifying directories based on lack of extension though - even if it is just an option I have a feeling it would generate issues, but I'll give it some thought.  Thanks for your input. I'll try to get this as soon as I have some spare time.  In the meantime, pull requests are always welcome ;)

**Comment by fshost** [comment]
I may look into adding functionality for non-sequential directory iteration in the future but for the time being I'm closing this issue.
