### ISSUE TITLE
options doesn't work

### ISSUE THREAD

**Issue by elyas74** [fshost/node-dir#42]
I pass an object to control your modules options part but does not work
```
dir.paths(path, function(err, paths) {
  if (err) throw err;
  console.open(paths.dirs);
},{
  recurse : false,
  shortName : true
});
```
I do something wrong?

**Comment by AckerApple** [comment]
The option is named "recursive" not "recurse"

**Comment by AckerApple** [comment]
Also, you might be using the NPM version and currently ONLY the github version supports the options you are trying to use.
