### ISSUE TITLE
listFiles

### ISSUE THREAD

**Issue by justincy** [fshost/node-dir#7]
Would be useful to have a function called `listFiles` that functions exactly like `readFiles` except it only returns the filename and not the file's contents. `files` doesn't have all of the fancy options that `readFiles` does. Or perhaps it could just be an additional option in `readFiles`.

**Comment by fshost** [comment]
The readFiles method already exists for working with the contents of each file.  Please look at that section of the readme.  This method is just for getting a list of files.  As such there is really no reason to duplicate the functionality found in the readFiles method.

**Comment by fshost** [comment]
@tkdan235 I have done as you suggested and added the examples to the readme.
