### ISSUE TITLE
Potential "stack size exceeded"

### ISSUE THREAD

**Issue by polkovnikov-ph** [fshost/node-dir#9]
The default stack depth in Node.js is 492 while max file path in almost every filesystem is unlimited (http://en.wikipedia.org/wiki/Comparison_of_file_systems). Use explicit stack, please.

**Comment by fshost** [comment]
If needed you can change the default stack depth for node.  It is implicitly assumed that the use cases for this are within node parameters, and if not, perhaps another library would be a better choice.  However, if you are having an actual error (as opposed to theoretical) please provide the code and use case (or contribute a pull request) and I might be willing to revisit this.  (If I have failed to understand your concern, perhaps you could be more explicit.)
